Feature/id 366/filter incidents
CampusDelSaber/api-rest-hermes pull request #9
Opened 2023-06-21 16:04 UTC by luiggymamani

What I did?
Send incidents using filters by type of incident.
The filters, filter by one or more types and you can use them to filter with the nearby incidents filter that had been created.

How I dis?
Using the find method and putting the filter-like query parameter

Why I did?
To send this data when the user selects a type of incident to see

2023-06-21 19:28 UTC, SebasBarra02 approved these changes

2023-06-21 23:03 UTC, zrock-dev requested changes
The name of the file `src/controller/responses/incidentRes.js` is pretty ambiguous since it can be interpreted as `incidentResources`, `incidentResponses` or even `incidentResults`

2023-06-21 23:03 UTC, zrock-dev commented on src/controller/responses/incidentRes.js
> +const getNearIncidents = async (types, longitude, latitude, radius) => {
By adding this parameter, you are constraining the queries to type, but what if we want to have all nearby incidents?

2023-06-21 23:03 UTC, zrock-dev commented on src/controller/responses/incidentRes.js
>  		return [];
Could you log this error? So there will be a registry.

2023-06-21 23:41 UTC, luiggymamani commented on src/controller/responses/incidentRes.js
> +const getNearIncidents = async (types, longitude, latitude, radius) => {
the method has a conditional if the types query is null, in that case the method just return the near incidents

2023-06-21 23:53 UTC, zrock-dev commented on src/controller/responses/incidentRes.js
> +const getNearIncidents = async (types, longitude, latitude, radius) => {
cool, it's solved then

2023-06-22 00:14 UTC, zrock-dev approved these changes

2023-06-22 01:31 UTC, saletG08 approved these changes
I don't have any comments

2023-06-22 01:31 UTC, merged